In [1]:
import pandas as pd

In [5]:
data = pd.Series([1,2,3,4,4,5], index=['a','b','c','d','e','k'])
data

a    1
b    2
c    3
d    4
e    4
k    5
dtype: int64

In [6]:
data = pd.DataFrame([1,2,3,4,4,5])
data

   0
0  1
1  2
2  3
3  4
4  4
5  5

In [8]:
lst = [[1,2,3,4,5], [6,7,8,9,0]]
df = pd.DataFrame(lst)
df

   0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0

In [9]:
dict = {'name' : ['Kamal','Nimal', 'Saman'], 'marks' : [67,45,92]}
df = pd.DataFrame(dict) 
df

    name  marks
0  Kamal     67
1  Nimal     45
2  Saman     92

In [10]:
dict2 = {'name' : ['Kamal','Nimal', 'Saman'], 'marks' : [67,45,92]}
df2 = pd.DataFrame(dict2) 
df2

    name  marks
0  Kamal     67
1  Nimal     45
2  Saman     92

In [12]:
pd.concat([df,df2])

    name  marks
0  Kamal     67
1  Nimal     45
2  Saman     92
0  Kamal     67
1  Nimal     45
2  Saman     92

In [13]:
pd.concat([df,df2], axis=1)

    name  marks   name  marks
0  Kamal     67  Kamal     67
1  Nimal     45  Nimal     45
2  Saman     92  Saman     92